# Site settings
name: kuerbb
email: kuerbb@aliyun.com
author: ChenYusheng
url: http://www.kuerbb.com
resume_site: 
github: https://github.com/kuerbb/
baseurl: ""
description: Actually, less is more!
meta_description: 陈雨声;个人博客;人生坎坷路、拼搏不止步;
motto: The two most important days in your life are the day you were born and the day you find out why.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: kuerbb
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : DL_YSYN
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light